### ISSUE TITLE
Elaborate and explain why it poses a security risk in README

### ISSUE THREAD

**Issue by niftylettuce** [cusspvz/proxywrap#32]
Can you update this sentence in the README and provide reasoning as to why?

> Disabling this option poses a security risk; it should be enabled in production.

**Comment by solderjs** [comment]
I'm curious too.

It seems that if something local were hacking away on a 127.0.0.1 bound port that it would just as well be able to send proxy headers, and that if it were bound 0.0.0.0 then... you have two problems.

**Comment by gugu** [comment]
I think if HAProxy is not configured to send proxy headers then the client can send proxy headers instead. Using this option will ensure HAProxy is configured correctly

**Comment by cusspvz** [comment]
@niftylettuce @coolaj86 @gugu in case it is disabled, your instances will accept traffic that doesn't start with the proxy protocol. When strict is enabled, all non-PROXY Protocol traffic will get dropped, meaning that in case someone gets access to those instances, either because they're publicly exposed or somehow a bad actor gets internal exposure, they can:
- inject forwarding related headers to the request and pose a security risk depending on the application.
- override security measures that are usually set at the LB-level such as rate-limiting, instance stickiness, etc.

Although setting it as `strict` doesn't ensure a level of security, it helps to decrease the impact of information-gathering and DoS strategies.

But in case you don't want bad actors, crawlers, and scrappers snooping around, just make sure you properly set iptable rules/firewalls and block public access to/from your instances.
